# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: tour
    weight: 10
  - name: News
    url: post
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Publications
    url: publication
    weight: 40
  - name: Tools
    url: tool
    weight: 50
    - name: Projects
    url: project
    weight: 60  
  - name: Resources
    url: resource
    weight: 70
  - name: Events
    url: event
    weight: 80  
  - name: Join us
    url: join
    weight: 90
  - name: Contact
    url: contact
    weight: 100
